# Generated by Django 2.2.1 on 2019-05-25 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ig_handle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('followers', models.IntegerField(default=0)),
                ('profile_pic', models.CharField(blank=True, max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'influencers_celebrity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fb_id', models.CharField(blank=True, max_length=255)),
                ('profile_pic', models.CharField(blank=True, max_length=255)),
                ('locale', models.CharField(blank=True, max_length=48)),
                ('timezone', models.IntegerField(default='+7')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('score', models.IntegerField(default=100)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'common_profile',
                'managed': False,
            },
        ),
    ]
