# Generated by Django 2.2.1 on 2019-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(choices=[('enterprise', 'Enterprise'), ('professional', 'Professional'), ('individual', 'Individual'), ('all-access', 'All Access'), ('free', 'Influencer')], default='free', max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=55)),
                ('details', models.CharField(blank=True, max_length=254)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stripe_plan_id', models.CharField(max_length=55)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=55)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=55)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
